"use strict";
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.employee = exports.driver = exports.manager = exports.admin = exports.owner = exports.user = exports.superadmin = exports.OrgAc = exports.Orgstatements = exports.AdminAc = exports.Adminstatements = void 0;
var access_1 = require("better-auth/plugins/access");
var access_2 = require("better-auth/plugins/admin/access");
var access_3 = require("better-auth/plugins/organization/access");
exports.Adminstatements = __assign(__assign({}, access_2.defaultStatements), { department: ["create", "read", "update", "delete"], shift: ["create", "read", "update", "delete", "assign"], employee: ["create", "read", "update", "delete", "assign", "transfer"], driver: ["create", "read", "update", "delete", "assign", "activate", "rate"], vehicle: ["create", "read", "update", "delete", "assign", "activate", "maintenance"], vehicleCategory: ["create", "read", "update", "delete"], vehicleAvailability: ["create", "read", "update", "delete"], vehicleRequest: ["create", "read", "update", "delete", "approve", "reject"], route: ["create", "read", "update", "delete", "assign", "activate", "optimize"], stop: ["create", "read", "update", "delete", "assign", "sequence"], payroll: ["create", "read", "update", "delete", "process", "approve", "export"], payrollReport: ["create", "read", "update", "delete", "generate", "export"], billing: ["read", "write", "manage", "export"], notification: ["create", "read", "update", "delete", "send", "broadcast"], analytics: ["read", "export", "dashboard", "reports"], reports: ["create", "read", "export", "schedule"], data: ["read", "write", "export", "import", "backup", "restore"] });
exports.AdminAc = (0, access_1.createAccessControl)(exports.Adminstatements);
exports.Orgstatements = __assign(__assign({}, access_3.defaultStatements), { department: ["create", "read", "update", "delete"], shift: ["create", "read", "update", "delete", "assign"], employee: ["create", "read", "update", "delete", "assign", "transfer"], driver: ["create", "read", "update", "delete", "assign", "activate", "rate"], vehicle: ["create", "read", "update", "delete", "assign", "activate", "maintenance"], vehicleCategory: ["create", "read", "update", "delete"], vehicleAvailability: ["create", "read", "update", "delete"], vehicleRequest: ["create", "read", "update", "delete", "approve", "reject"], route: ["create", "read", "update", "delete", "assign", "activate", "optimize"], stop: ["create", "read", "update", "delete", "assign", "sequence"], payroll: ["create", "read", "update", "delete", "process", "approve", "export"], payrollReport: ["create", "read", "update", "delete", "generate", "export"], billing: ["read", "write", "manage", "export"], notification: ["create", "read", "update", "delete", "send", "broadcast"], analytics: ["read", "export", "dashboard", "reports"], reports: ["create", "read", "export", "schedule"], data: ["read", "write", "export", "import", "backup", "restore"] });
exports.OrgAc = (0, access_1.createAccessControl)(exports.Orgstatements);
exports.superadmin = exports.AdminAc.newRole(__assign(__assign({ department: ["create", "read", "update", "delete"], shift: ["create", "read", "update", "delete", "assign"], employee: ["create", "read", "update", "delete", "assign", "transfer"], driver: ["create", "read", "update", "delete", "assign", "activate", "rate"], vehicle: ["create", "read", "update", "delete", "assign", "activate", "maintenance"], vehicleCategory: ["create", "read", "update", "delete"], vehicleAvailability: ["create", "read", "update", "delete"], vehicleRequest: ["create", "read", "update", "delete", "approve", "reject"], route: ["create", "read", "update", "delete", "assign", "activate", "optimize"], stop: ["create", "read", "update", "delete", "assign", "sequence"], payroll: ["create", "read", "update", "delete", "process", "approve", "export"], payrollReport: ["create", "read", "update", "delete", "generate", "export"], billing: ["read", "write", "manage", "export"], notification: ["create", "read", "update", "delete", "send", "broadcast"], analytics: ["read", "export", "dashboard", "reports"], reports: ["create", "read", "export", "schedule"], data: ["read", "write", "export", "import", "backup", "restore"] }, access_2.adminAc.statements), access_3.ownerAc.statements));
exports.user = exports.AdminAc.newRole(__assign({}, access_2.userAc.statements));
exports.owner = exports.OrgAc.newRole(__assign({ department: ["create", "read", "update", "delete"], shift: ["create", "read", "update", "delete", "assign"], employee: ["create", "read", "update", "delete", "assign", "transfer"], driver: ["create", "read", "update", "delete", "assign", "activate", "rate"], vehicle: ["create", "read", "update", "delete", "assign", "activate", "maintenance"], vehicleCategory: ["create", "read", "update", "delete"], vehicleAvailability: ["create", "read", "update", "delete"], vehicleRequest: ["create", "read", "update", "delete", "approve", "reject"], route: ["create", "read", "update", "delete", "assign", "activate", "optimize"], stop: ["create", "read", "update", "delete", "assign", "sequence"], payroll: ["create", "read", "update", "delete", "process", "approve", "export"], payrollReport: ["create", "read", "update", "delete", "generate", "export"], billing: ["read", "write", "manage", "export"], notification: ["create", "read", "update", "delete", "send", "broadcast"], analytics: ["read", "export", "dashboard", "reports"], reports: ["create", "read", "export", "schedule"] }, access_3.ownerAc.statements));
exports.admin = exports.OrgAc.newRole(__assign({ department: ["create", "read", "update", "delete"], shift: ["create", "read", "update", "delete", "assign"], employee: ["create", "read", "update", "delete", "assign", "transfer"], driver: ["create", "read", "update", "delete", "assign", "activate", "rate"], vehicle: ["create", "read", "update", "delete", "assign", "activate", "maintenance"], vehicleCategory: ["create", "read", "update", "delete"], vehicleAvailability: ["create", "read", "update", "delete"], vehicleRequest: ["create", "read", "update", "delete", "approve", "reject"], route: ["create", "read", "update", "delete", "assign", "activate", "optimize"], stop: ["create", "read", "update", "delete", "assign", "sequence"], payroll: ["create", "read", "update", "delete", "process", "approve", "export"], payrollReport: ["create", "read", "update", "delete", "generate", "export"], billing: ["read", "write", "manage", "export"], notification: ["create", "read", "update", "delete", "send", "broadcast"], analytics: ["read", "export", "dashboard", "reports"], reports: ["create", "read", "export", "schedule"] }, access_3.adminAc.statements));
exports.manager = exports.OrgAc.newRole(__assign({ department: ["read"], shift: ["create", "read", "update", "delete", "assign"], employee: ["read", "update", "assign"], driver: ["read", "update", "assign", "activate", "rate"], vehicle: ["read", "update", "assign", "activate", "maintenance"], vehicleCategory: ["read"], vehicleAvailability: ["create", "read", "update", "delete"], vehicleRequest: ["read", "update"], route: ["create", "read", "update", "delete", "assign", "activate", "optimize"], stop: ["create", "read", "update", "delete", "assign", "sequence"], payroll: ["create", "read", "update", "process", "export"], payrollReport: ["create", "read", "update", "generate", "export"], billing: ["read", "export"], notification: ["create", "read", "update", "send", "broadcast"] }, access_3.memberAc.statements));
exports.driver = exports.OrgAc.newRole(__assign({ department: ["read"], shift: ["read"], employee: ["read"], driver: ["read"], vehicle: ["read"], vehicleCategory: ["read"], vehicleAvailability: ["read"], route: ["read"], stop: ["read"] }, access_3.memberAc.statements));
exports.employee = exports.OrgAc.newRole(__assign({ department: ["read"], shift: ["read"], employee: ["read"], driver: ["read"], vehicle: ["read"], vehicleCategory: ["read"], route: ["read"], stop: ["read"] }, access_3.memberAc.statements));
